introduce new tool 'bee fetch'
this tool allows us to install bee packages from remote repositories

* add URL(s) (or directories) to the file ${XDG_CONFIG_HOME}/bee/beeremote
 (one URL per line; comments beginning with '#')

* execute 'bee fetch' to get all information about remote bee packages from the server(s)

* execute 'bee install' for the desired remote package(s) to install
 (the bee package will be retrieved and installed from the remote repository)

* 'bee list' also lists available remote packages

* remote repositories must contain a file 'pkglist' which contains 'ls *bee*'
 (one package per line)

diff --git a/src/bee-install.sh.in b/src/bee-install.sh.in
--- a/src/bee-install.sh.in
+++ b/src/bee-install.sh.in
@@ -234,6 +234,35 @@ function do_install() {
 
     assert "x${file}" != "x"
 
+    local extension=${file##*.}
+
+    if [ "${extension}" = "beeremote" ]; then
+        # retrieve file
+        local remotefile=${file}
+
+        file=${file%.beeremote}
+        file="${file}.bee.tar.bz2"
+
+        if [ ! -f "${file}" ]; then
+            local url=$(cat ${remotefile})
+
+            if [ "${url:0:1}" = "/" ]; then
+                cp "${url}" "${file}"
+            else
+                wget -q -O "${file}" "${url}"
+            fi
+        fi
+
+        if [ ! -s "${file}" ]; then
+            echo >&2 "bee-install: ${file}: Could not retrieve package file"
+            rm -f "${file}" # in case of 0 byte file
+            exit 1
+        fi
+
+        # success; clean up
+        rm -f ${remotefile}
+    fi
+
     local pkg=$(${BEE_BINDIR}/beeversion --format="%A" ${file} 2>/dev/null)
     local fullname=$(${BEE_BINDIR}/beeversion --pkgfullname ${file} 2>/dev/null)
     local maxinst=
